"""empty message

Revision ID: 25b0df90cb11
Revises: 
Create Date: 2017-04-21 17:50:49.524348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b0df90cb11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=100), nullable=True),
    sa.Column('pword_hint', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('wish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wish_name_url', sa.String(length=250), nullable=True),
    sa.Column('wish_id', sa.Integer(), nullable=True),
    sa.Column('wish_descript', sa.String(length=40), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('thumbnail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['wish_id'], ['person.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wish')
    op.drop_table('person')
    # ### end Alembic commands ###
